openapi: 3.0.1
info:
  title: Swagger
  version: '1.0'
paths:
  /api/v1/Comanda:
    get:
      tags:
        - Comanda
      parameters:
        - name: fecha
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComandaResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComandaResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComandaResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    post:
      tags:
        - Comanda
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComandaRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/ComandaRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ComandaRequest'
      responses:
        '201':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ComandaResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ComandaResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ComandaResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /api/v1/Comanda/{id}:
    options:
      tags:
        - Comanda
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ComandaGetResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ComandaGetResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ComandaGetResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /api/v1/Mercaderia: 
    get:
      tags:
        - Mercaderia
      parameters:
        - name: tipo
          in: query
          schema:
            type: integer
            format: int32
        - name: nombre
          in: query
          schema:
            type: string
        - name: orden
          in: query
          schema:
            type: string
            default: ASC
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MercaderiaGetResponse'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MercaderiaGetResponse'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MercaderiaGetResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    options:
      tags:
        - Mercaderia
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MercaderiaRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/MercaderiaRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/MercaderiaRequest'
      responses:
        '201':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MercaderiaResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/MercaderiaResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/MercaderiaResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '409':
          description: Conflict
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
  /api/v1/Mercaderia/{id}:
    get:
      tags:
        - Mercaderia
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MercaderiaResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/MercaderiaResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/MercaderiaResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    options:
      tags:
        - Mercaderia
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MercaderiaRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/MercaderiaRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/MercaderiaRequest'
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MercaderiaResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/MercaderiaResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/MercaderiaResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '409':
          description: Conflict
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
    delete:
      tags:
        - Mercaderia
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/MercaderiaResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/MercaderiaResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/MercaderiaResponse'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '409':
          description: Conflict
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/BadRequest'
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
            text/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
components:
  schemas:
    BadRequest:
      type: object
      properties:
        message:
          type: string
          nullable: true
      additionalProperties: false
    ComandaGetResponse:
      type: object
      properties:
        mercaderias:
          type: array
          items:
            $ref: '#/components/schemas/MercaderiaGetResponse'
          nullable: true
        formaEntrega:
          $ref: '#/components/schemas/FormaEntrega'
        total:
          type: number
          format: double
        fecha:
          type: string
          format: date-time
      additionalProperties: false
    ComandaRequest:
      type: object
      properties:
        mercaderias:
          type: array
          items:
            type: integer
            format: int32
          nullable: true
        formaEntrega:
          type: integer
          format: int32
      additionalProperties: false
    ComandaResponse:
      type: object
      properties:
        mercaderias:
          type: array
          items:
            $ref: '#/components/schemas/MercaderiaComandaResponse'
          nullable: true
        formaEntrega:
          $ref: '#/components/schemas/FormaEntrega'
        total:
          type: number
          format: double
        fecha:
          type: string
          format: date-time
      additionalProperties: false
    FormaEntrega:
      type: object
      properties:
        id:
          type: integer
          format: int32
        descripcion:
          type: string
          nullable: true
      additionalProperties: false
    MercaderiaComandaResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
          nullable: true
        precio:
          type: number
          format: double
      additionalProperties: false
    MercaderiaGetResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
          nullable: true
        precio:
          type: number
          format: double
        tipo:
          $ref: '#/components/schemas/TipoMercaderiaResponse'
        imagen:
          type: string
          nullable: true
      additionalProperties: false
    MercaderiaRequest:
      type: object
      properties:
        nombre:
          type: string
          nullable: true
        tipo:
          type: integer
          format: int32
        precio:
          type: number
          format: double
        ingredientes:
          type: string
          nullable: true
        preparacion:
          type: string
          nullable: true
        imagen:
          type: string
          nullable: true
      additionalProperties: false
    MercaderiaResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
          nullable: true
        tipo:
          $ref: '#/components/schemas/TipoMercaderiaResponse'
        precio:
          type: number
          format: double
        ingredientes:
          type: string
          nullable: true
        preparacion:
          type: string
          nullable: true
        imagen:
          type: string
          nullable: true
      additionalProperties: false
    TipoMercaderiaResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        descripcion:
          type: string
          nullable: true
      additionalProperties: false
